### ISSUE TITLE
ORM推荐

### ISSUE THREAD

**Issue by colinaaa** [ttzztztz/Rabbit-OJ-Backend#1]
最近看到一个不错的ORM，是基于代码生成的，不过处于开发阶段，可能不是很稳定

https://github.com/facebookincubator/ent

**Comment by colinaaa** [comment]
顺便可以考虑用postgresql 好像有很多黑魔法

**Comment by ttzztztz** [comment]
ありがとうございます！

**Comment by colinaaa** [comment]
﻿どういたしまして

发自我的iPhone
